---

- name: add nginx repo
  yum_repository:
    name: nginx
    description: Nginx Repository
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes

- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true 
    state: enabled 
    immediate: yes
  ignore_errors: yes

- name: http service state
  systemd: 
    name: nginx 
    state: started 
    enabled: yes
