---
- name: install php-fpm and deps
  dnf: 
    name:
      - php
      - php-fpm
      - php-enchant
      - php-mbstring
      - php-mysqlnd
      - php-xml
      - php-gd
      - php-json
      - php-common
    enablerepo: epel,remi,remi-php74
    state: latest 
  notify: restart php-fpm

- name: disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: copy php-fpm configuration
  template: 
    src: wordpress.conf 
    dest: /etc/php-fpm.d/
    #  notify: restart php-fpm
