---
- name: download WordPress
  get_url: 
    url: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/srv/wordpress-{{ wp_version }}.tar.gz"

- name: extract archive
  unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz 
    dest: /srv/
    copy: no 

- name: add group "wordpress"
  group: name=wordpress

- name: add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: fetch random salts for WordPress config
  get_url: 
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: /tmp/salts

- name: read solts file
  command: cat /tmp/salts
  register: "wp_salt"

- name: create WordPress database
  mysql_db: 
    name: "{{ wp_db_name }}" 
    state: present

- name: create WordPress database user
  no_log: true
  mysql_user: 
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}" 
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    update_password: always
    state: present

- name: copy WordPress config file
  template: 
    src: wp-config.php 
    dest: /srv/wordpress/

- name: change ownership of WordPress installation
  file: 
    path: /srv/wordpress/ 
    owner: wordpress 
    group: wordpress 
    state: directory 
    recurse: yes

- name: install SEManage
  dnf: 
    pkg: 
      - python3-policycoreutils
      - policycoreutils-python-utils
      - setools-console
    state: present

- name: set the SELinux policy for the Wordpress directory
  sefcontext:
    target: "/srv/wordpress(/.*)?"
    setype: httpd_sys_content_t
    state: present

- name: set the SELinux policy for wp-config.php
  sefcontext:
    target: "/srv/wordpress/wp-config.php"
    setype: httpd_sys_script_exec_t
    state: present

- name: set the SELinux policy for wp-content directory
  sefcontext:
    target: "/srv/wordpress/wp-content(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: set the SELinux policy for the *.php files
  sefcontext:
    target: "/srv/wordpress/.*.php?"
    setype: httpd_sys_script_exec_t
    state: present

- name: set the SELinux policy for the Upgrade directory
  sefcontext:
    target: "/srv/wordpress/wp-content/upgrade(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: set the SELinux policy for the Uploads directory
  sefcontext:
    target: "/srv/wordpress/wp-content/uploads(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present

- name: set the SELinux policy for the wp-includes php files
  sefcontext:
    target: '/srv/wordpress/wp-includes/.*.php'
    setype: httpd_sys_script_exec_t
    state: present

- name: set httpd_can_network_connect flag on and keep persistent
  # for theme and plugin install, update
  seboolean: 
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: set httpd_unified flag on and keep persistent
  seboolean:
    name: httpd_unified
    state: yes
    persistent: yes

- name: set the SELinux on all the Files
  command: restorecon -Rv /srv/wordpress

- name: start php-fpm service
  systemd: 
    name: php-fpm 
    state: started 
    enabled: yes
