---
# This playbook will install MariaDB and create db user and give permissions.

- name: install mariadb package
  dnf: 
    name:
      - mariadb-server
      - python3-PyMySQL
      - python3-libselinux
      - python3-libsemanage
    state: latest

- name: configure SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any 
    state: true 
    persistent: yes

- name: create mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb 

- name: create mariadb log file
  file: 
    path: /var/log/mysqld.log 
    state: touch 
    owner: mysql 
    group: mysql 
    mode: 0775

- name: start mariadb Service
  systemd: 
    name: mariadb 
    state: started 
    enabled: yes

