---
# timezone 
- name: set timezone to Asia/Tokyo
  timezone: 
    name: Asia/Tokyo

#install chrony ntp server
- name: install chrony
  yum:
    name: chrony
    state: latest

- name: comment out default servers
  replace:
    path: /etc/chrony.conf
    regexp: '^(server \d+.centos.pool.ntp.org iburst)'
    replace: '# \1'

- name: add jst servers
  blockinfile:
    dest: /etc/chrony.conf
    state: present
    content: |

      # ntp servers
      server ntp.jst.mfeed.ad.jp iburst
      server ntp.nict.jp iburst

- name: restart chrony
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

# add repository
- name: add epel repository
  yum: name={{ item }}
  with_items:
    - epel-release

# disable epel for defoult repository
- name: disable epel for default
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo


- name: install remi repo.
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

# firewalld 
- name: check firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True

- name: firewalld open ports by service
  firewalld:
    permanent: true
    immediate: true
    state: enabled
    service: "{{item}}"
  with_items:
    - http
