---
# timezone 
- name: set timezone to Asia/Tokyo
  timezone: 
    name: Asia/Tokyo

#install chrony ntp server
- name: install chrony
  dnf:
    name: chrony
    state: latest

- name: comment out default server pools
  replace:
    path: /etc/chrony.conf
    regexp: '^(pool \d+.centos.pool.ntp.org iburst)'
    replace: '# \1'

- name: add jst servers
  blockinfile:
    dest: /etc/chrony.conf
    state: present
    content: |

      # ntp servers
      server ntp.jst.mfeed.ad.jp iburst
      server ntp.nict.jp iburst

- name: restart chrony
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

# add repository
- name: add epel repository
  dnf:
    name: epel-release
    state: latest

# disable epel for defoult repository
- name: disable epel for default
  replace: 
    dest: /etc/yum.repos.d/epel.repo
    regexp: "enabled *= *1" 
    replace: "enabled=0"

- name: install remi repo.
  dnf:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: import remi GPG key.
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

# firewalld 
#- name: firewalld open ports by service
#  firewalld:
#    permanent: true
#    immediate: true
#    state: enabled
#    service: http
